Migration to Scala 2.10.2, Akka 2.2 abd SBT 0.12.3
This commit updates Hector to use the latest Scala 2.10.2
and Akka 2.2 while switching to SBT 0.12.4

Hector compiles and runs albeit some problems. Next steps
include getting rid of dead letters in IOActor (potentially
due to sender reference) and general deprecation warnings.

Migration included the following steps:

- Upgrade SBT properties, using new xsbt-web-plugin

- Added new scalac options: -Yinline-warnings, -feature
  and -language:implicitConversions

- Upgrading to scalatest 1.9.1

- Got rid of ImmutableSortedSet in HtmlEmitter due
  to scalac bug resulting in runtime VerifyError[1]

- Hack to get rid of a scalac bug in JsClientSupport
  leading to VerifyError at runtime[2]

- Migrated imports to scala.concurrent and friends

- Importing context.dispatcher where necessary

- receive is no longer protected

- Promise.successful is now Future.successful

- Using case exception: Throwable where appropriate

- Getting rid of tell() if not necessary

- Using Try instead of Either (see RequestActor)

[1] Stack trace:
java.lang.NoSuchMethodError:
com.google.common.collect.ImmutableSortedSet.of(Ljava/lang/Comparable;Ljava/lang/Comparable;Ljava/lang/Comparable;Ljava/lang/Comparable;Ljava/lang/Comparable;Ljava/lang/Comparable;[Ljava/lang/Object;)Lcom/google/common/collect/ImmutableSortedSet;
at hector.html.emitter.HtmlEmitter$.<init>(HtmlEmitter.scala:866)

[2] Error message:
FAILED HectorFilter: java.lang.VerifyError: (class:
hector/js/JsClientSupport$, method: <init> signature: ()V) Expecting to
find object/array on stack